### ISSUE TITLE
clean_times.py returns encoding error, "KeyError: 'Collision Time'

### ISSUE THREAD

**Issue by markstos** [ids-digi/moco-crash-data#9]
I'm having difficulty running `clean_times.py` to check the intermediate results. 

Initially, I got this error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 243644: invalid start byte
```

It seems to be suggesting the input data is not Unicode, but I was using the same source data, so I don't see I would get a different result there. More likely, I'm using a different version of the Pandas library, which behaves differently. It would be helpful if the versions of libraries used was mentioned to help reproduce the results. 

I worked around the issue with a code modification:

```
   return pd.read_csv(in_file, encoding_errors = 'replace')
```

That says to replace characters in the CSV with some other character. This allowed the code to proceed beyond that issue. But then I got the following the error, which have not resolved. 

Here the complaint seems to be that a key named "Collision Time" is being added to a CSV data structure when it already exists.

```
  File "/usr/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Collision Time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mark/git/moco-crash-data/./cleaning-workflow/cleaning-scripts/clean_times.py", line 75, in <module>
    CLEAN_DF1 = clean_1318(DF_13_18, 'Collision Time')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mark/git/moco-crash-data/./cleaning-workflow/cleaning-scripts/clean_times.py", line 50, in clean_1318
    df[time_col] = df[time_col].apply(clean_times_1318)
                   ~~^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'Collision Time'
```

**Comment by markstos** [comment]
I see now I made a mistake. I thought skipping the "main data cleaning" script was optional, but it was not. It appears to rename some columns including one named "Collision Time", which seems that it prevent running into the case I ran into.
